### ISSUE TITLE
Update macroquad and other dependencies

### ISSUE THREAD

**Issue by sparshg** [sparshg/asteroids-genetic#3]
Macroquad 0.4.4 has some breaking changes which need to be addressed. Also a few other dependencies are outdated

**Comment by WindowGenerator** [comment]
Hi!
Can I take this issue?

**Comment by sparshg** [comment]
Sure

**Comment by WindowGenerator** [comment]
Hi!
I almost done this issue, just waiting for a bug solution [here](https://github.com/not-fl3/macroquad/issues/664).

**Comment by sparshg** [comment]
I see, you can share your progress by opening a PR, thanks!
